### ISSUE TITLE
Separate each tool for different repos

### ISSUE THREAD

**Issue by v1rtl** [NoxFly/tools#1]
Don't put everything into one repo because it is very inconvenient to use.

Create 2 different repos instead and just add a link to them in README, smth like this:

### My cool libs
[d&d](https://github.com/NoxFly/dnd)

Also, use a bundler, such as [Rollup](https://github.com/rollup/rollup) or [Microbundle](https://github.com/developit/microbundle) to compile your libraries to different module systems (cjs, esm, system, umd) so we can use them as NPM package, `<script>` or with `import`.

And yeah, don't forget to publish them on https://unpkg.com and https://npmjs.com

**Comment by NoxFly** [comment]
Thanks for your tip, I'll do this when I'll have the time to :)
